<?php


namespace backend\controllers;


use common\models\Medias;
use yii\web\BadRequestHttpException;
use yii\web\Response;

class AjaxController extends BaseController
{
    public function init()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionRemoveMedia()
    {
        $media_id = \Yii::$app->request->post('media_id');
        try {
            $media = Medias::findOne($media_id);
            if (!$media) {
                throw new BadRequestHttpException('Media not found!');
            }
            return $media->delete();
        } catch (\Exception $exceptione) {
            throw new BadRequestHttpException($exceptione->getMessage());
        }
    }

}
