<?php


namespace frontend\controllers;


use yii\web\Response;

class AjaxController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->response->format = Response::FORMAT_JSON;
    }
    function actionProduct()
    {
        return [];
    }
}
