<?php


namespace backend\modules\controllers;


use common\models\MenuConfig;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;

class MenuController extends BaseActiveFilterController
{

    public $modelClass = MenuConfig::class;

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['create']);
        return $actions;
    }

    public function actionCreate()
    {
        $post = \Yii::$app->request->post();
        $model = MenuConfig::findOne(['name' => ArrayHelper::getValue($post, 'name')]);
        if (!$model) {
            throw new BadRequestHttpException('không tìm thấy menu!');
        }
        $item = ArrayHelper::getValue($post, 'item');

    }
}
