<?php


namespace backend\modules\controllers;


use backend\models\UploadForm;
use common\helper\HelperFunction;
use yii\base\Exception;
use yii\web\BadRequestHttpException;
use yii\web\UploadedFile;

class UploadController extends BaseActiveController
{
    public $modelClass = false;

    public function actions()
    {
        $action = parent::actions();
        unset($action['index']);
        return $action;// TODO: Change the autogenerated stub
    }

    protected function verbs()
    {
        return [
            'index' => ['POST'],
        ];
    }

    /**
     * @return bool
     * @throws BadRequestHttpException
     */
    public function actionIndex()
    {
        if (\Yii::$app->request->isPost) {
            $model = new UploadForm();
            try {
                $model->load(\Yii::$app->request->post(), "");
                return $model->upload();
            } catch (BadRequestHttpException | Exception $e) {
                throw new BadRequestHttpException($e->getMessage());
            }
        }
        throw new BadRequestHttpException("Post only");
    }

}
