<?php

namespace common\models;

use common\helper\HelperFunction;
use Yii;

/**
 * This is the model class for table "archives".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $slug
 * @property int|null $active
 * @property string|null $description
 * @property int|null $created_at
 * @property int|null $updated_at
 */
class Archives extends BaseModel
{
    /**
     * {@inheritdoc}
     */
    public $avatar;
    public $media_id;

    public static function tableName()
    {
        return 'archives';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['active', 'created_at', 'updated_at'], 'integer'],
            [['description'], 'string'],
            [['name', 'slug'], 'string', 'max' => 255],
            [['slug'], 'unique'],
            [['avatar', 'media_id'], 'safe'],
            [['name', 'slug'], 'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'slug' => 'Slug',
            'active' => 'Active',
            'description' => 'Description',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function extraFields()
    {
        return ['avatar', 'media', 'media_id']; // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        if ($this->media) {
            $this->avatar = HelperFunction::getImage($this->media->path);
        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        Medias::saveObj($this->media_id, $this->id);

    }

    public function getMedia()
    {
        return $this->hasOne(Medias::className(), ['obj_id' => 'id'])->where([
            '{{medias}}.type' => Medias::ARCHIVE_TYPE
        ]);
    }

}
