<?php


namespace common\models;


use yii\db\ActiveRecord;
use function Webmozart\Assert\Tests\StaticAnalysis\null;

class BaseModel extends ActiveRecord
{


    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created_at = time();
        }
        $this->updated_at = time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
//        $this->updated_at = date('d/m/Y', $this->updated_at);
//        $this->created_at = date('d/m/Y', $this->created_at);
    }
}
