<?php


namespace common\models;


use yii\base\Model;

class Common extends Model
{
    public $email;
    public $favicon;
    public $hotline_1;
    public $hotline_2;
    public $site_name;
    public $site_description;
    public $address_1;
    public $address_1_en;
    public $address_2;
    public $address_2_en;
    public $logo_header;
    public $logo_footer;
    public $site_name_en;
    public $site_description_en;
    public $fanpage_script;
    public $map_iframe;
    public $about_us;
    public $about_us_en;
    public static function tableName()
    {
        return 'setting'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['email', 'site_name', 'hotline_1',
                'hotline_2', 'address_1', 'address_2',
                'logo_header', 'logo_footer', 'site_description',
                'address_1_en', 'site_name_en', 'site_description_en',
                'address_2_en',
                'favicon','map_iframe','fanpage_script',
                'about_us','about_us_en'
            ], 'string']
        ];
    }

}
