<?php


namespace common\models;


class CommonModel extends BaseModel
{
    public static function tableName()
    {
        return 'setting'; // TODO: Change the autogenerated stub
    }

    public function getMedia()
    {
        return $this->hasOne(Medias::className(), ['id' => 'value'])
            ->where(['medias.type' => 'Common[logo_header]'])
            ->orWhere(['medias.type' => 'Common[logo_footer]']);
    }
}
