<?php

namespace common\models;

use common\helper\HelperFunction;
use Yii;
use yii\web\BadRequestHttpException;

/**
 * This is the model class for table "products".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $slug
 * @property string|null $status
 * @property string|null $content
 * @property string|null $language
 * @property string|null $excerpt
 * @property string|null $attributes
 * @property float|null $default_price
 * @property float|null $default_sale_type
 * @property float|null $default_sale_price
 * @property int|null $default_archive
 * @property int|null $created_at
 * @property int|null $updated_at
 */
class Products extends BaseModel
{
    public $avatar;
    public $thumbnails;
    public $media_id;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['content', 'attributes'], 'string'],
            [['default_price', 'default_sale_type', 'default_sale_price'], 'number'],
            [['created_at', 'updated_at', 'default_archive'], 'integer'],
            [['name', 'slug', 'excerpt'], 'string', 'max' => 255],
            [['status', 'language'], 'string', 'max' => 50],
            [['slug'], 'unique'],
            [['avatar', 'thumbnails', 'media_id'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function extraFields()
    {
        return ['avatar', 'archives', 'meta', 'media_id', 'thumbs', 'thumbnails', 'meta']; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'slug' => 'Slug',
            'status' => 'Status',
            'content' => 'Content',
            'excerpt' => 'Excerpt',
            'attributes' => 'Attributes',
            'default_price' => 'Default Price',
            'default_sale_type' => 'Default Sale Type',
            'default_sale_price' => 'Default Sale Price',
            'language' => 'Ngôn ngữ',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'default_archive' => 'Danh mục mặc định'
        ];
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        if ($this->media) {
            $this->avatar = HelperFunction::getImage($this->media->path);
            $this->media_id = $this->media->id;
        }
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        try {
            Medias::removeObj($this->id, Medias::PRODUCT_THUMB_TYPE);
            Medias::removeObj($this->id, Medias::PRODUCT_TYPE);
            ProductsArchive::removeRef($this->id);
        } catch (\Exception $exception) {
            throw new BadRequestHttpException($exception->getMessage());
        }

    }

    public function getMeta()
    {
        return $this->hasOne(SeoMeta::className(), ['obj_id' => 'id'])
            ->where(['obj_type' => SeoMeta::META_PRODUCT]);
    }

    public function getMedia()
    {
        return $this->hasOne(Medias::className(), ['obj_id' => 'id'])
            ->andFilterWhere(['type' => Medias::PRODUCT_TYPE]);
    }

    public function getThumbs()
    {
        return $this->hasMany(Medias::className(), ['obj_id' => 'id'])
            ->andFilterWhere(['type' => Medias::PRODUCT_THUMB_TYPE]);
    }

    public function getArchives()
    {
        return $this->hasMany(ProductsArchive::className(), [
            'product_id' => 'id'
        ])->with('archive');
    }

    public function getDefaultArchive()
    {
        return $this->hasOne(Archives::className(), [
            'id' => 'default_archive'
        ]);
    }

    public function getFirstArchive()
    {
        return $this->hasOne(ProductsArchive::className(), [
            'product_id' => 'id'
        ])->with('archive');
    }
}
